### ISSUE TITLE
RDD v2.2 - #7 Relâcher les contraintes

### ISSUE THREAD

**Issue by nfaugout** [LuccaSA/RestDrivenDomain#101]
On me demande régulièrement de mettre moins de contraintes sur les TEntity. On a déjà fait une partie du boulot, mais il reste des cas en effet où on se demande pourquoi on doit implémenter tel ou tel propriété.

Sur EntityBase, on pourrait déjà virer Id, Name, car de toute façon ils sont déjà imposés par IEntityBase en get seulement, ce qui semble mieux adapter à la plupart des situations.

Sur les Repo ou les Collection, on pourrait imaginer des Repo ou des Collection de type non-EntityBase. Il faudrait alors faire la distinction entre un type qui a une API racine (ex : User), et un type qui n'a qu'une sous API (ex : Move ou Friend), et qui n'a sans doute pas besoin d'être un EntityBase.

Reste à voir les modalité de ce changement.

@Poltuu pour répondre à ton point sur le côté artificiel des contraintes actuelles, je précise qu'on est dans le cadre d'un framework qui vise à créer des API REST. Les concepts de id, name, url leur sont fortement liés, ça ne tombe pas du ciel. Et le fait que l'interface s'appelle IEntityBase et non pas IUrlable, INamable et IIdable n'est pas un manque de découplage, mais une volonté de structuration. En éclatant les interfaces, certes on découple le code, mais le découpage est artificiel pour le coup, car il ne correspond plus à un concept fort. Donc attention à ne pas chercher à trop découper, au risque d'arriver à qq chose de "technique" qui manquerait de concepts clés.

**Comment by Poltuu** [comment]
Les interfaces, leur nommage et leur existence doit venir des systèmes qui consomment ces interfaces.
`IUrlable `est en effet artificiel, jusqu'au moment ou un "`IMailService`" demande en paramètre de méthode précisément un "`IUrlable`" pour afficher une url. Dès lors, l'existence de l'interface est justifiée et nécessaire. De même, il ne faut surtout pas forcer au `IMailService` de prendre en entrée un `IEntityBase`, car cela ne correspond pas à ses problèmes, n'est pas SOLID etc... C'est à ce moment là, lorsqu'un système/composant justifie l'existence d'une nouvelle interface, que la nouvelle interface doit exister.

Tout ça pour en venir à notre problème, quelle est la responsabilité d'`IEntityBase` ? Quel système discute avec cette interface ? Aujourd’hui, de très nombreux, puisque c'est L'interface consommée sur toute la chaîne de l'api. Ce que je défends, c'est qu'il faut couper cette interface, selon les composants qui la consomme:
 - au niveau des repos, seule la présence d'un id est nécessaire, donc là en effet, un `IIdable` est nécessaire et suffisant
 - au niveau des Collections, aucun besoin spécifique (si je ne m'abuse). Donc les collection reprend les contraintes des sous-systèmes qu'il utilise (donc sans doute `IIdable`)
 - au niveau des controllers, c'est là que l'on peut commencer à voir, comme tu le précises, que l'on fait un framework à API REST. Et donc c'est LE composant qui peut demander que les objets qu'il s'apprête à exposer aient les propriétés "id", "name", et "url". c'est normale, c'est le seul endroit où on se sert de ces propriétés !

Ce que je défends donc, c'est qu'un découpage est possible et nécessaire, sans perdre les propriétés dont on discute (surtout pas). On le voit bien d'ailleurs, il existe dans Lucca de nombreux exemples d'obejts nécessitant un repo mais non exposés en frontal. Et donc n'ayant pas besoin d'url ou name, et même, ne sachant que faire de ces propriétés en fait.

**Comment by nfaugout** [comment]
OK je vois l'idée.

Ce qui me gène, c'est quand on nomme une interface à partir des propriétés qu'elle contient et non à partir du concept auquel elle correspond.

Par ex dans DDD on parle d'Entité, et on dit qu'une entité a forcément un ID uniquement.

Delà on peut donc dire que les entités doivent implémenter IIdable, mais on peut aussi dire qu'une entité doit implémenter IEntity, parce que c'est un concept à part entière, qq soit les contraintes qu'on met derrière.

Donc ça se trouve IEntity n'implémente QUE IIdable sans rien d'autre. Et dans 6 mois on y ajoutera IUrlable.

Autrement dit, on voit qu'on a des interfaces "techniques", qui correspondent à des propriétés ou des comportements techniques, et des interfaces "fonctionnelles" ou "philosophiques", qui correspondent à des concepts durables.

Et je pense qu'on devrait garder les 2.

**Comment by Poltuu** [comment]
Alors, j'ai bien réfléchi, et je pense que je ne suis pas d'accord : on ne devrait garder que les interfaces utilisées et utilisables, et non pas pour leurs valeurs "intrinsèques" ou philosophiques ou fonctionnelles. Je m'explique

Je ne pense pas qu'il soit illégitime que l'interface `IEntity` existe. Je ne pense pas non plus qu'il soit déraisonnable de l'appeler ainsi, même si elle ne porte qu'une propriété du style `Id`, voire même si ça définition est la suivante:

`interface IEntity : IIdable { } `

C'est d'ailleurs mieux d'avoir du code expressif, donc j'aime même ce nommage, et le préfère à IIdable (cf plus bas aussi). Ce dont je suis contre, c'est la définition et l'hébergement d'interfaces à valeur symbolique justifiée (IEntity) SANS que cette interface n'ait de sens pour le système, càd sans que cette interface ne soit consommée entièrement. En un sens, je suis également contre insérer des contraintes qui ont du sens intrinsèque pour l'objet, pour la valeur symbolique portée par l'objet, SANS qu'elles aient du sens dans le cadre du système qui le consomme.

Je vais te donner un exemple d'interface que je souhaiterais supprimer dans Lucca, en suivant la même logique, au risque de te faire hérisser le poil, l'interface `Lucca.Domain.IBusinessObject`. Pourquoi?
Je ne dis pas que cette interface ne porte pas de sens, on a bien tous compris son sens. Mais le fait est, que X années après la naissance de Lucca en DDD, cette interface n'est simplement pas utilisée. Certaines classes annoncent en effet bien implémenter cette interface, mais cette interface n'est réclamée par aucun système, la rendant donc de facto _inutile_. Je ne vois pas bien comment justifier son existence dès lors, elle n'offre aucun service à celui qui l'implémente : pourquoi donc l'implémenter ?

Pour conclure, je pense donc la même chose au sujet de IEntity. Soit on arrive a faire en sorte que cette interface emmagasine un certain nombre de contraintes correspondant à des besoins de consommation de composants de RDD, ce qui justifie alors pleinement la vie et l'existence de cette interface, soit cette interface n'est de facto pas utilisée et ne sert donc à rien, et doit être supprimée; c'est alors sans doute un aveu d'échec soit de ce concept, qui n'a peut-être pas de sens dans notre contexte, ou bien un échec de notre librairie, qui n'a pas bien compris ce concept.
Personnellement, je pense, à la lumière de nos discussions notamment, que le concept IEntity a du sens au niveau web, càd régit bien la manière dont un objet de niveau inférieur doit être exposé au monde extérieur (on le voit avec la contrainte d'exposer une url et un nom, contraintes vraiment de la couche Web). Par contre, ce concept perd de sens au fur et mesure qu'on se rapproche du domain et de la couche de persistance. Ce n'est pas forcément étonnant d'ailleurs, car ce n'est pas un concept DDD, qui manipule des aggrégat etc etc, mais un concept d'api rest et sa notion de ressource.


__________________________________________

Concernant le nommage des interfaces, je suis d'accord. C'est d'ailleurs pas une très bonne chose de nommer les interfaces par leurs propriétés, c'est un anti-pattern (je sais plus ou j'ai lu ça..). Comme tu dis, les interfaces devraient avoir un nom naturel qui émerge, comme l'interface animal implémentée par dog et cat. C'est en fait également vrai pour les interfaces en "XXX-service".
Mais trouver un bon nom est encore plus compliqué, parce que ce qui compte le _plus_, c'est de ne pas laisser de marge d'erreur quant à la compréhension de ce que demande telle ou telle interface. Dans ce cheminement, les interfaces en "xxx-able" sont un bon compromis en réalité, "je suis capable de xxx".

Par exemple, sur `IIdable<TKey>`, plusieurs idées peuvent venir:
 - `IKey` : attention, je ne suis pas une `IKey`, je peux _renvoyer_ une key, je _possède_ une key, ce n'est pas la même chose. De même, pourquoi Key tout à coup, alors que la propriété s'appelle Id ? N'est-ce pas la même chose ?
 - `IUnique<TKey>` : Unique ? unique de quoi ? Ne peut-on pas trouver deux fois le même objet avec le même ID ? Est-ce un singleton ? Unique temporellement ? Je ne connais pas non plus a priori le nom des propriétés exposées par cette interface
 - `IIdentifiable<TId>` : en fait à bien y réfléchir, ce nom est mieux 😕 . On peut _m'identifier_ avec un `Id` de type `TId`, c'est quand même clair. C'est assez proche de ce qui existe, mais ya plus d'intention, et est plus lisible que `IIdable<TKey>`

**Comment by GMouron** [comment]
Je trouve les remarques de Romain plutôt pertinentes.
Qui plus est, je pense qu'on peut très bien avoir une cohabitation entre des interfaces "techniques" et des interfaces "fonctionnelles", celles-ci étant sans doute un agrégat d'interfaces "techniques".
Le seul truc gênant, c'est qu'on  pas de moyen automatiques d'obliger l'utilisation d'interfaces "fonctionnelles" là où elle devrait être utilisées.
On peut simplement l'encourage via la code review notamment.

**Comment by Poltuu** [comment]
mais surtout, tu peux contraindre les gens à utiliser tes interfaces "fonctionnelles" si ce sont des contraintes à satisfaire pour utiliser tes composants "techniques" ;)

**Comment by nfaugout** [comment]
+1 pour IIdentifiable<TId>

On est d'accord j'ai l'impression, car je ne défend évidemment pas le fait de garder des interfaces qui ne sont jamais utilisées ou quoi.

Concernant `IBusinessObject`, j'avais oublié cette interface, mais en effet si elle est implémentée à moitié, forcément elle perd de son intérêt et personne ne l'utilise ! Ca qui ne veut pas dire que ce n'était pas une bonne idée, juste qu'on n'est pas allé au bout du concept.

Donc imposer des interfaces pour imposer des interfaces, en effet, je suis contre ;)

Ce que je voudrais éviter, c'est que demain les contraintes soient tellement souples qu'une équipe crée une API REST basée sur des ObjectValue par ex, qui n'ont ni ID ni aucune propriété imposée. C'est la porte ouverte à tout et n'importe quoi.

Donc ce que je dis, c'est qu'il faut quand même trouver un point commun entre tous les objets du Domain qu'on expose au niveau racine de nos API, et matérialiser ça sous forme d'interface/contrainte. Et si ce point commun c'est IIdentifiable, alors pour moi ça signifie qu'on n'aura pas été assez loin dans nos réflexions.

Tout comme Guillaume, je pense qu'au final l'interface qu'on va trouver sera une agrégation d'interfaces techniques, qui permettra à une équipe de ne déclarer qu'une seule contrainte au lieu de 4 ou 5.

Et en effet comme tu dis il faut raisonner par couche, ce qu'on n'a pas fait jusqu'à maintenant, et qui peut sans doute nous permettre d'arriver à un compromis.

Càd que du point de vue du Domain, on parle d'aggrégats (IAggregate), de racine d'aggrégat (IAggregateRoot), etc...

Du point de vue Infra, à priori on parle de pouvoir identifier les ressource par leur ID, donc IIdentifiable me semble nécessaire et suffisant.

Du pont de vue Web, on parle de ressource (REST), donc probablement un IResource.

Sauf que RDD, c'est aussi la "promesse" de ne pas avoir 3 couches de mapping avec des DTO (web <> domain, domain <> infra), donc mettre une contrainte IResource sur une classe Web revient à mettre cette contrainte sur la racine d'aggrégat du Domain !

Donc au final, on se rapproche pas mal d'une interface IEntity : IResource, IIdentifiable, qui sera consommée selon les couches selon telle ou telle interface.

Enfin, tu dis que le DDD ne parle pas d'entité, je t'invite à relire un peu l'état de l'art sur le sujet, ça parle d'Entity partout (ex : http://culttt.com/2014/04/30/difference-entities-value-objects/)

**Comment by Poltuu** [comment]
bon bah on est d'accord alors :)

**Comment by nfaugout** [comment]
🤝 

TODO : Lister ici les interfaces, ce qu'elles contiennent et dans quelle couche elles sont.

**Comment by rducom** [comment]
Sur le sujet de base : relâcher les contraintes, j'aimerais (même si Nico je sais que tu est contre), permettre techniquement aux consommateurs d'implémenter facilement le cas où un Controller<T1> peut se faire injecter une Collection<T2> qui lui se fait injecter un Repo<T3>. 
Avec dans la plupart des use-case, T1 exposé web étant un sous-ensemble de T2 (bo, objet fort de notions domaine internes), et T3 pouvant être n'importe quoi.
Oui celà va rajouter une couche de mapping à qui veut implémenter un controller/collection/repo de cette façon, MAIS si on permet le cas simple (T1==T2==T3) par default, et qu'on permet aussi le cas "custom" lorsqu'on en a besoin, ça me parait tout à fait sain.
La promesse de RDD (implémenter facilement et rapidement un crud pour un BO) est respecté, et on permet les cas plus complexes.

La motivation est qu'à l'heure actuelle, je vois des trucs un peu hacky dans le monolithe (via le patcher), qui pourraient être simplifiés avec cette approche. D'autre part en analyse de CA, on est revenu maintes fois sur ce débat, et le besoin me semble vraiment fort.

+1 aussi pour `IIdentifiable<TKey>`

Petit point C# : une interface n'a de sens QUE si elle a vocation à permettre la substitution d'une implémentation par une autre. Si elle n'a pas cette vocation, alors elle est inutile. Pour de l'injection de dépendance par exemple, aucun besoin d'avoir systématiquement des interfaces (ça peut paraître contre intuitif, mais c'est le cas). (@Poltuu ça vaudrait que coup de clean les devtools d'ailleurs ;) )

**Comment by nfaugout** [comment]
Même si en effet je trouve que la solution (T1 != T2 !=T3) au problème que tu décris (avoir l'impression de mettre du Web dans Domain ou de l'Infra dans Domain) n'est pas scalable, et constitue souvent une renoncement au problème d'origine qui est probablement que les concepts n'ont pas été assez creusés, je n'ai pas de pb avec l'idée de dire qu'un Controller T1 peut travailler avec une Collection T2 qui utilise un Repo T3, sans que T1, T2 ou T3 aient de lien entres eux.

Je sais que c'est laisser le loup dans la bergerie, mais à la limite ça me permettra de continuer à militer pour l'approche T1=T2=T3, sans que ce soit pris pour un argument d'autorité.

Après faut voir ce que ça implique au niveau des contraintes, mais je suis certain que Romain va se faire un plaisir de nous faire une PR dans ce sens, voire qu'il l'a déjà sous le coude et attendait un tel moment de faiblesse pour la sortir 😄

**Comment by Poltuu** [comment]
@rducom une interface n'a de sens QUE si elle a vocation à permettre la substitution d'une implémentation par une autre =>ok. donc si j'ai vocation à faire des tests sur mes objets, je peux garder mes interfaces ? C'est pas ma faute si devtools n'a pas de bug :D

@nfaugout j'avais en effet dév un repo dans ma pr qui renvoyait un type T1, en allant taper sur un type T2 en base, mais ce n'était donc pas la même chose, puisque T2 n'était pas exposé. Et également, il n'existait qu'un seul niveau de changement de type. Mais si c'est si gentiment demandé, je te ferait une PR du style ;)

**Comment by rducom** [comment]
En fait l'enjeu d'un design T123 (quel joli nom de code) se situe au niveau du typage generics de la chaine controlleur, app, collection, repo. C'est LA contrainte a relâcher (et j'ai pas de solution obvious now, juste une idée un peu nazi qui consiste à anéantir totalement TEntity / IIdentifiable)

**Comment by nfaugout** [comment]
@rducom @Poltuu avec la PR en cours sur IEntityBase j'ai l'impression que cette issue est addressée, même si la PR ne fait pas exactement ce qui est dit ici.

Donc si ça vous va on ferme cette issue puisque la PR est presque mergée.
