### ISSUE TITLE
Virer la contrainte IEntityBase sur les repos

### ISSUE THREAD

**Issue by nfaugout** [LuccaSA/RestDrivenDomain#116]
En effet autant une Collection n'expose QUE des entitybase, autant un repo peut concerner des objets qui n'ont pas vocation à être exposés au niveau API.

Par ex dans LuccaFaces, je crée une table `cheatings` pour historiser toutes les tentatives de triche que je vois passer, et ça peut arriver par plusieurs portes (la création d'un Game, l'envoi des Guesses, ...).

Donc toutes les Collections associées vont prendre en dépendance le repo des `Cheating` qui ne sont pas des `EntityBase`, et ajouter un élément dedans.

**Comment by Poltuu** [comment]
done
