### ISSUE TITLE
Virer les xxByIds

### ISSUE THREAD

**Issue by nfaugout** [LuccaSA/RestDrivenDomain#121]
Actuellement on a :

- une méthode Get( ) générique
- des méthodes GetById( ) et GetByIds( ) qui in-fine appellent Get( ) avec des filtres sur les ids
- des méthodes UpdateByIds( ) & co qui appellent GetByIds( ) puis font leur code métier propre

Avec le nouveau paradigme qui consiste à dire que sur une collection ne peut pas avoir le détail des propriétés des entités, mais que sur une entité en particulier on peut tout voir, je me demande si les xxByIds( ) ont encore du sens.

Et ça permettrait également de découpler le Get( ) et le GetById( ) comme suggéré dans https://github.com/LuccaSA/RestDrivenDomain/issues/104.

**Comment by Poltuu** [comment]
je dois dire que je ne vois pas pourquoi les GetByIds sont devenus obsolètes. Il existe de nombreuses manières de récupérer plusieurs ids d'une collection.
Après, ce ne sont pas des méthodes très importantes de l'ordre du sucre syntaxique, donc je n'y suis pas spécialement attachés, mais je pense que leur utilité reste entière

**Comment by nfaugout** [comment]
Ils ne sont pas obsolètes, mais comme tu dis ce sont des sucres qui ne sont pas forcément très utiles d'avoir au niveau du framework. Sachant qu'en plus de toute façon derrière ça appelle le Get( ) normal.

**Comment by rducom** [comment]
C'est quand même assez pratique point de vue dev d'avoir une méthode permettant de se dispenser de créer un Query à la mano. Point de vue framework, une surface d'API (c# j'entends) qui expose des méthodes GetByKey c'est fréquent

**Comment by rducom** [comment]
Ok, merci de la précision, j'ai raté le `s`
