### ISSUE TITLE
Rework PropertySelector

### ISSUE THREAD

**Issue by nfaugout** [LuccaSA/RestDrivenDomain#130]
Un `PropertySelector` permet d'encapsuler une `Expression` (ex : `u => u.Manager.Name`) en la découpant en Expression intermédiaires (ex : `u => u.Manager > m => m.Name`), ce qui permet ensuite de faire de l'introspection plus facilement dans 2 concepts de la `Query` : `Fields` et `Filters`

Pour les `Filters`, on n'a pas besoin d'une structure en arbre, car on ne filtre toujours que sur 1 propriété à la fois.

En revanche, pour les `Fields`, on veut parfois plusieurs sous fields d'un même field parent (ex : `fields=manager[id,name]`)

On voit donc qu'on a 2 besoins différents, et voici une approche pour y répondre :

- au niveau de `Query`, un `IEnumerable<Field>` pour énumérer les fields de premier niveau demandés
- idem pour les filtres, un `IEnumerable<Filter>`

Ensuite, 2 classes de sélection des propriétés :

- `PropertySelector` pour sélectionner 1 propriété, utilisé dans `Filter`
- `PropertiesSelector` pour sélectionner N propriétés, qui contient un `IEnumerable<PropertiesSelector> Children` pour stocker ses propriétés

NB : le type `PropertiesSelector` correspond à l'ancienne version de `PropertiesSelector`.

`Fields` utiliserait donc un `PropertiesSelector` pour stocker les fields à sélectionner.

Ensuite au niveau sérialisation & co, on fait les adaptations qui vont bien et ça devrait passer.

**Comment by Poltuu** [comment]
je n'ai pas lu dans le détail mais immédiatement, ct un des chantiers de ma pr https://github.com/LuccaSA/RestDrivenDomain/pull/37
qui s'attachait à limiter ses responsabilités et à mieux structurer une Query notamment

**Comment by nfaugout** [comment]
Tu pourras reprendre cette partie là de ce que tu avais fait alors ;)

Et t'assigner cette Issue si tu veux t'en occuper.

**Comment by Poltuu** [comment]
done
