### ISSUE TITLE
oldEntity is not always oldEntity

### ISSUE THREAD

**Issue by nfaugout** [LuccaSA/RestDrivenDomain#131]
Lors d'un POST/PUT, la validation est jouée 2 fois : 

- une fois explicitement dans le Create ou le Update de la Collection
- une fois si on est sous EF lors du SaveChanges

La 2ème fois, à priori, le oldEntity n'est pas la bonne référence, ça pointe en réalité vers l'entité modifiée.

Reproduit sur Lucca, à voir si ça touche aussi RDD.

**Comment by bastienguillon** [comment]
Le monolithe n'utilise pas RDD (pas à ma connaissance en tout cas), tu penses que le problème est également présent sur RDD ?

**Comment by nfaugout** [comment]
@Poltuu je déterre ça suite au KPI Tech d'hier.

Comme tu l'indiquais, c'est la validation EF qui est en cause ici, on voit qu'on ne la maîtrise pas bien, qui plus est avec l'injection de dépendance (est-ce qu'EF va transmettre les dépendances prévues dans la méthode Validate d'une entité ? J'ai bien peur que non, et qu'il "compte" sur de l'injection via le constructeur, ce qu'on évite de faire sur des entités en général !)

Donc je suis plutôt d'accord avec toi, càd qu'on devrait virer la validation EF.

De toute façon y'a la "validation" SQL qui va jouer, donc avec la validation métier jouée par le Domain + la validation SQL pour éviter les side effects non maîtrisés, on est déjà pas mal.

Le dernier point, c'est ce dont parlait Séb, càd tu crées une entité T1 à laquelle tu rattaches une entité T2 alors que la validation de cette entité T2 est faite dans SON Domain à elle. Si tu l'accroches à l'arrache sur T1, la validation de T2 ne va donc pas jouer.

Mais pour moi, c'est un antipattern de faire comme ça, il faut plutôt :
- appeler la Collection de T2 pour créer T2 (sa validation va alors jouer)
- attacher T2 à T1

Si ces 2 étapes sont respectées, normalement y'a plus de raison de laisser la validation EF.

Si c'est OK, ça sous entend que pour virer la validation EF, soit c'est possible via du paramétrage (?), soit il faut créer des interfaces/méthodes de validation custom qui ne sont pas celles prévues par .NET, et que EF ne pourra donc pas détecter. Tu peux creuser ce point ?

**Comment by Poltuu** [comment]
il suffit que les objets n'implémentent ps IValidatableObject, je peux le faire dans un PR si tu veux

**Comment by Poltuu** [comment]
je suis en train de regarder, rdd n'a pas de validation ef, donc on est bon sur ce point là
