### ISSUE TITLE
Sérialisation Json

### ISSUE THREAD

**Issue by nfaugout** [LuccaSA/RestDrivenDomain#133]
Je me suis rendu compte que le `IContractResolver` enregistré dans la DI ne servait pas à grand chose car injecté nulle part dans RDD.

Du coup la sérialisation des réponses sort en PascalCase.

J'ai adapté un retour de controller web dans un projet pour compenser, cf https://github.com/LuccaSA/Lucca.Auth/commit/3fffa68e46407ee344e08991345300e69c2ac2a4.

Mais il faudrait intégrer ça dans RDD nativement (par défaut je veux dire, et qu'on puisse overrider).

Sachant que [Metadata](https://github.com/LuccaSA/RestDrivenDomain/blob/master/Web/RDD.Web/Models/Metadata.cs#L45) ne devrait pas présupposer de la sérialisation, et donc avoir des props en PascalCase et pas de `ToDictionnary( )`.

Je sais que le modèle de sérialisation est en avance dans Lucca, ce serait bien de le récupérer de gérer ça par la même occasion.

**Comment by Poltuu** [comment]
fixed
