### ISSUE TITLE
ReadOnlyRepository.Set(query) ignores the query

### ISSUE THREAD

**Issue by bastienguillon** [LuccaSA/RestDrivenDomain#146]
The method `ReadonlyRepository.Set(query)` does not actually use the query given in its parameters:

``` C#
protected virtual IQueryable<TEntity> Set(Query<TEntity> query)
{
     return StorageService.Set<TEntity>();
}
```

Therefore, calling `repository.Set(query).FirstOrDefault()` will only execute the following SQL query, which does not contain any filter and hence does not return the expected result: 

``` SQL
select top(1) [columns...]
from [entityTable]
```

**Comment by nfaugout** [comment]
Je passe en français pour plus de clarté.

La méthode Set( ) a comme responsabilité d'aller chercher le plus gros ensemble de TEntity disponible, càd sans filtre, sans paging, sans les droits, etc...

Ces fonctionnalités sont ajoutées par dessus (ApplyFilters, ApplyPaging, ..) plus tard dans le processus.

Ici c'est l'implémentation par défaut, qui n'est pas censé utilisée query en effet. Càd que l'ensemble des TEntity global ne doit pas dépendre de la façon dont un user l'interroge.

Sauf que pour faire plaisir à des utilisateurs de Rdd, j'ai certainement à un moment donné mis query en paramètre car ils en avaient besoin dans leur override.

Pour moi la bonne solution, c'est donc plutôt de virer query de cette méthode.

**Comment by Poltuu** [comment]
c'est utiliser pour la suppression logique

**Comment by nfaugout** [comment]
En effet, mais à mauvais escient je pense, d'ailleurs je sais que tu n'as jamais aimé ça non plus ;)

Il y a 2 choses :

- soit on est sur une suppression d'apparence physique, avec un `internal bool isDeleted` qui n'a pas vocation à être exposé via l'API, auquel cas le Set( ) va systématiquement virer les entrées avec isDelete=true

- soit on est sur un archivage, ou une pseudo suppression logique, avec un `public bool isActive` qui est exposé via l'API, et par défaut on veut créer un filtre qui ne renvoie que les entités avec isActive=true

Dans le premier cas, on n'a pas besoin de la query dans le Set( ), et dans le 2ème cas, on pourrait déporter le filtre dans le ApplyFilter( )

**Comment by nfaugout** [comment]
@Poltuu je suggère donc qu'on vire `query` du Set( ), t'en penses quoi ?

**Comment by Poltuu** [comment]
dans poplee talent, on gère la suppression logique au niveau d'ef core. également, tu peux dans une requête en particulier désactiver les filtres par défaut sans pb

Ca ne me choque pas qu'on vire la query du set pour plus de clarté
