### ISSUE TITLE
RDD vs Rdd

### ISSUE THREAD

**Issue by nfaugout** [LuccaSA/RestDrivenDomain#149]
Ce commit https://github.com/LuccaSA/RestDrivenDomain/commit/704f4c2ad4a9744b4bb6ac4d50508dc1d18240f2 remet RDD à la place de Rdd.

Il me semblait que nos conventions étaient :
- acronyme de 2 lettres => les 2 lettres en majuscule, genre IO
- acronyme de plus de 2 lettres => PascalCase comme un "mot" normal

**Comment by rducom** [comment]
C'est Mvc et pas MVC.
Les conventions énoncés sont bonnes
