### ISSUE TITLE
branche 3.0

### ISSUE THREAD

**Issue by rducom** [LuccaSA/RestDrivenDomain#159]
Vu les gros breaking changes qui s'annonces dans les PR en cours (https://github.com/LuccaSA/RestDrivenDomain/pull/158, https://github.com/LuccaSA/RestDrivenDomain/pull/151, https://github.com/LuccaSA/RestDrivenDomain/pull/142, https://github.com/LuccaSA/RestDrivenDomain/pull/141 ), je propose de créer une branche 3.0 pour regrouper l'ensemble des breaking changes.

**Comment by Poltuu** [comment]
ça me convient

**Comment by rducom** [comment]
la stratégie convenue est d'avancer sur master. Les branches de release sont crées une fois les releases faites pour LTS. ex : https://github.com/LuccaSA/RestDrivenDomain/tree/releases/2.2.3
