### ISSUE TITLE
Generic type contraint in IDependencyInjectionResolver 

### ISSUE THREAD

**Issue by MaximeBonobots** [LuccaSA/RestDrivenDomain#16]
I would like to define a custom resolver like this in RDD:

```c#
	public class SimpleInjectorResolver : IDependencyInjectionResolver
	{
		private readonly Container SimpleInjectorContainer;
		...
		public TInterface Resolve<TInterface>() where TInterface: class
		{
			return SimpleInjectorContainer.GetInstance<TInterface>();
		}
	}

```

but it requires a 'where T: class' in IDependencyInjectionResolver signatures, due to a type constraint in SimpleInjector resolver:

https://github.com/simpleinjector/SimpleInjector/blob/master/src/SimpleInjector/Container.Resolving.cs#L58

Is it OK to add it in RDD ?

**Comment by MaximeBonobots** [comment]
@nfaugout 
tu pourras me donner les droits pour pusher ?

**Comment by nfaugout** [comment]
C'est fait, j'ai créé une Team "RDD contributors" pour ajouter au fur et à mesure ceux qui veulent contribuer
