### ISSUE TITLE
Exception sur le CreateCandidates de l'ApiHelper

### ISSUE THREAD

**Issue by sylvainjourdan** [LuccaSA/RestDrivenDomain#162]
Si j'envoie un JsonArray dans un post, le CreateCandidates me renvoie une exception lors de l'appel à 
new Candidate<TEntity, TKey>(rawInput, el as JsonObject).

Pour corriger le problème temporairement, j'ai overrider le comportement du CreateCandidates par celui-ci 

```
public override IEnumerable<ICandidate<TEntity, TKey>> CreateCandidates()
{
    string rawInput = _httpContextHelper.GetContent();
    var jsonObject = ParseIntoArray(rawInput);
    return jsonObject.Content.Select(el => new Candidate<TEntity, TKey>(JsonConvert.SerializeObject(el.GetContent()), el as JsonObject));
}
```

**Comment by Poltuu** [comment]
fixed
