### ISSUE TITLE
IStorageService dans RDD.Infra : code smell ?

### ISSUE THREAD

**Issue by alexcarpe** [LuccaSA/RestDrivenDomain#170]
Dans le constructeur des AppController il y a l'injection de IStorageService  qui se trouve dans RDD.Infra et ça me fais bizarre car ça me semble la seule raison pour la quelle AppController a une dépendance envers la couche Infra.

- Faut il, peut-être, déplacer IStorageService dans la couche Domain ?
- Le constructeur du AppControlleur as-t-il besoin de toutes les méthodes de IStorageService ?

**Comment by nfaugout** [comment]
Check this out : https://github.com/LuccaSA/RestDrivenDomain/pull/171 ;)
