### ISSUE TITLE
Query parsing

### ISSUE THREAD

**Issue by nfaugout** [LuccaSA/RestDrivenDomain#180]
Il y a 2 PR en cours qui visent à revoir le parsing de la Query : https://github.com/LuccaSA/RestDrivenDomain/pull/164 et https://github.com/LuccaSA/RestDrivenDomain/pull/141.

Est-ce que, si vous voulez toujours faire passer ces PR, vous pouvez décrire brièvement les changements que vous comptez faire ? Et les bénéfices pour le framework.

**Comment by Poltuu** [comment]
je vais rebaser ma branche, et voir ce qu'il en est

**Comment by Poltuu** [comment]
ok, j'ai rebasé ma pr https://github.com/LuccaSA/RestDrivenDomain/pull/164

globalement, ya pas de modification profonde, juste une réorganisation pour simplifier les usages et les override. Ya quand même deux trois fixs par ci par là, notamment sur le post/put multiple, qui en l'état était simplement planté. (createcandidates planté).

Je vous laisse donc juger, je pense que c'est un paquet de bonnes évolutions, mais c'est pas critique. faut voir comment on s'organise pour fusionner ces idées et celles de la 141.

**Comment by rducom** [comment]
@Poltuu le principal changement que je souhaiterais que tu reporte sur ta PR est le découplage des différents parsings dans la classe : 

```csharp
    public static class QueryFactoryHelper
    {
        public static QueryFactory NewQueryFactory(HttpContext httpContext = null, PagingOptions rddOptions = null)
        {
            return new QueryFactory
            (
                new QueryMetadata(),
                NewQueryParsers(httpContext, rddOptions)
            );
        }

        public static QueryParsers NewQueryParsers(HttpContext httpContext = null, PagingOptions rddOptions = null)
        {
            var httpContextAccessor = new HttpContextAccessor()
            {
                HttpContext = httpContext ?? new DefaultHttpContext()
            };

            return new QueryParsers(
                new WebFilterParser(new QueryTokens(), httpContextAccessor),
                new PagingParser(httpContextAccessor, Options.Create(rddOptions ?? new PagingOptions())),
                new HeaderParser(httpContextAccessor),
                new OrderByParser(httpContextAccessor),
                new FieldsParser(httpContextAccessor)
                );
        }

    }
```

Les différents parsers sont registered via `TryAddSingleton<>` permettant ainsi d'ouvrir ces parsers à la surcharge.

D'autre part, plutôt que d'allouer et d'utiliser un dictionnaire intermédiaire pour le query string, j'attaque sur la https://github.com/LuccaSA/RestDrivenDomain/pull/141 directement le `HttpContext.Request.Query`. L'idée étant de réduire au maximum les allocations.

Il faut garder en tête que tout le code sur le query parsing est le "hot path" de RDD, c'est du code executé à chaque requête. Tout gain en performance est notable sur ce path.

**Comment by Poltuu** [comment]
- découper en parse :  nico a remonté la même chose, je vais le remettre en place 
 - pas de dico : je ne créé pas de dico à ce que je lis

https://github.com/LuccaSA/RestDrivenDomain/pull/164/files#diff-27822830f01158677e58993e83705b8c

**Comment by rducom** [comment]
Effectivement, c'est auparavant qu'il y avait un dico. Néanmoins, plutôt que de caster en `IEnumerable<KeyValuePair<string, StringValues>>` , ça pourrait être pas mal de taper directement dans `context.Request.Query` dans chaque parser.

**Comment by Poltuu** [comment]
tout ça a été réglé
