### ISSUE TITLE
IStorageService -> IUnitOFWork

### ISSUE THREAD

**Issue by Poltuu** [LuccaSA/RestDrivenDomain#187]
Je me faisais la réflexion suivante concernant `IStorageService`, maintenant défini dans l'application.

```c#
    public interface IStorageService : IDisposable
    {
        IQueryable<TEntity> Set<TEntity>() where TEntity : class;
        Task<IEnumerable<TEntity>> EnumerateEntitiesAsync<TEntity>(IQueryable<TEntity> entities) where TEntity : class;
        void Add<TEntity>(TEntity entity) where TEntity : class;
        void AddRange<TEntity>(IEnumerable<TEntity> entities) where TEntity : class;
        void Remove<TEntity>(TEntity entity) where TEntity : class;
        Task SaveChangesAsync();
        void AddAfterSaveChangesAction(Task action);
    }
```

Je trouve bizarre que la couche application définisse une telle interface, à base de `IQueryable`.

Je pense qu'elle devrait plutot définir une interface 
```c#
    public interface IUnitOfWork: IDisposable
    {
        Task SaveChangesAsync();
        void AddAfterSaveChangesAction(Task action);
    }
```

et laisser la définition de
```c#
    public interface IStorageService : IDisposable
    {
        IQueryable<TEntity> Set<TEntity>() where TEntity : class;
        Task<IEnumerable<TEntity>> EnumerateEntitiesAsync<TEntity>(IQueryable<TEntity> entities) where TEntity : class;
        void Add<TEntity>(TEntity entity) where TEntity : class;
        void AddRange<TEntity>(IEnumerable<TEntity> entities) where TEntity : class;
        void Remove<TEntity>(TEntity entity) where TEntity : class;
    }
```
à la couche infra.

Vous voyez l'idée ?

**Comment by rducom** [comment]
- Le `void AddAfterSaveChangesAction(Task action);`  devrait être externalisé dans une autre interface : l'implémentation concrete du `IUnitOfWork` va se faire injecter un DbContext, il sera alors tentant de l'utiliser en overridant le AddAfterSaveChanges
- D'autre part, le IDisposable est je pense non nécessaire sur les 2 interfaces, le DbContext devant être disposé à la fin de son LifeCycle Scoped
- Le proto de `void AddAfterSaveChangesAction(Task action);`
devrait plutôt être : 
`Task OnAfterSaveChangesAsync(() => Func<Task> action);`

**Comment by nfaugout** [comment]
@Poltuu en effet bonne remarque, on pourrait faire cette distinction. Mais attention, séparer ces 2 interfaces sous entend qu'elles pourraient fonctionner indépendamment. Or dans les fait j'ai l'impression qu'elles fonctionnent toujours ensemble..

Pour moi `AddAfterSaveChangesAction` a vocation à disparaître désormais qu'on a ouvert la voie à une couche Application plus "verbeuse" avec Poplee Talent. Càd que ce qui était injecté par le Domain dans `AddAfterSaveChangesAction` devrait être mise par le domaine dans une méthode (genre SendNotifications( ) par ex si c'est des mails qu'on veut envoyer après le commit), et c'est Application, qui après avoir joué l'action métier principal, puis commité, devrait appeler cette méthode.

Ainsi on peut virer le très adhoc et inexpressif `AddAfterSaveChangesAction`.

Pour en revenir à nos mouton, UOW est un pattern à part entière et je préfère qu'on ne le laisse pas entrer dans Rdd par la petite porte...

**Comment by Poltuu** [comment]
Ok pour virer `AddAfterSaveChangesAction`, pareil, inutilisé et désormais remplacé.

A bien regarder le code et le Unit of work pattern, je pense qu'on est déjà rentré dedans par la petite porte, mais avec notre `IStorageService `comme unitofwork.

Je ne souhaite pas rentrer dans des débats intenses sur le sujet du unitofwork, ce que je souhaiterais fixer avant tout, c'est l'exposition des membres `IQueryable<TEntity> Set<TEntity>()` (et autre) dans la couche application, qui n'ont rien à faire là franchement et qui est vraiment contraire à la philosophie rdd, et perturbant je pense.

Qu'est-ce que tu pourrais proposer pour corriger ça ?

**Comment by nfaugout** [comment]
`IStorageService : IUnitOfWork` ?

Ainsi, on voit bien le lien entre les 2, on laisse `IUnitOfWork` dans Application et on remet `IStorageService` dans l'Infra.

Par contre au niveau injection, je ne sais pas comment dire à l'injecteur que c'est la même instance qui devra être utilisée pour les 2 interfaces !

**Comment by nfaugout** [comment]
> Je vais quand même rajouter que si les interfaces étaient indépendante (càd sans héritage entre elles), cela aurait pu garantir que les repos ne puissent pas faire de .SaveChanges(), ce qui me parait quand même assez cool.

Je suis d'accord, et ça renforce l'idée que les commits ne doivent se faire QUE depuis la couche Application, mais dans ce cas comment tu ferais pour l'injection ?

**Comment by Poltuu** [comment]
dans c cas ya deux manières équivalentes :

```c#
services.TryAddScoped<IStorageService, EFStorageService>();
services.TryAddScoped<IUnitOfWork>(s => s.GetService<IStorageService>() as EFStorageService);

```
ou alors

```c#
services.TryAddScoped<EFStorageService>();
services.TryAddScoped<IStorageService>(s => s.GetService<EFStorageService>());
services.TryAddScoped<IUnitOfWork>(s => s.GetService<EFStorageService>());

```

Je préfère la seconde.
Je pars sur une version sans héritage alors ?

**Comment by Poltuu** [comment]
J'ai fait la version correspondante si ça te convient
https://github.com/LuccaSA/RestDrivenDomain/compare/uow_2?expand=1
