### ISSUE TITLE
MemberwiseClone ne clone pas les references

### ISSUE THREAD

**Issue by rducom** [LuccaSA/RestDrivenDomain#197]
`MemberwiseClone()` utilisé actuellement comme méthode Clone() par default ne clone pas les propriétés de type références : il ne fait que copier l'adresse de la référence.

En ce sens : un objet cloné à l'aide de cette méthode n'est pas vraiment cloné : seul les types valeur sont clonés. Si une modification est effectuée une sous-propriété du clone, alors l'original est lui aussi modifié. Cf [la doc](https://docs.microsoft.com/en-us/dotnet/api/system.object.memberwiseclone?redirectedfrom=MSDN&view=netframework-4.7.2#remarks)

> The MemberwiseClone method creates a shallow copy by creating a new object, and then copying the nonstatic fields of the current object to the new object. If a field is a value type, a bit-by-bit copy of the field is performed. If a field is a reference type, the reference is copied but the referred object is not; therefore, the original object and its clone refer to the same object. 

Le **gros danger** est le risque d'effectuer des modifications involontaires d'objets.

Une solution est d’effectuer un clone via sérialisation. 
Une autre par reflection récursive.

**Comment by Poltuu** [comment]
nan mais attends, moi j'ai encore mieux. Je pense intimement qu'on devrait virer cette étape de clone, car personne ne l’utilise (la preuve comme tu viens de le monter, elle est plantée ! ) Ca vient d'un vieux besoin cleemy, et personne d'autre n'a jamais utilisé ce truc. Pourtant, ça pollue toutes les classes.

Je suis absolument pour supprimer cette "fonctionnalité", qui peut être remplacée par de nombreuses techniques simples au sein des collections, déjà en l'état

**Comment by rducom** [comment]
Ce que je souhaite introduire avec https://github.com/LuccaSA/RestDrivenDomain/pull/192 c'est la possibilité de proprement discarder des modifications faites sur un objet référencé via le DbContext.

Sans l'étape clone, c'est pas possible.

Mais en attendant, pour résoudre cette issue purement et simplement, oui c'est la bonne solution.

**Comment by nfaugout** [comment]
Je suis d'accord avec Romain. Plutôt que de s'évertuer à proposer des méthodes de hooks genre onBeforeUpdate/onAfterUpdate qui n'ont pas de sens métier explicite, on devrait simplifier à mort le `UpdateAsync( )` en virant ces méthode, et donc l'étape de Clone qui va avec.

Si un projet veut injecter des hooks dans le Update il peut l'override en ajoutant du code avant/après le `base.UpdateAsync( )` et le tour est joué.

**Comment by rducom** [comment]
Où est-ce que je parle de méthode de hook ici ?????
Relis le message : 
> Ce que je souhaite introduire avec #192 c'est la possibilité de proprement discarder des modifications faites sur un objet référencé via le DbContext.

**Comment by rducom** [comment]
La nuit m'a porté conseil : il vaut mieux interdire by design la possibilité de manipuler le DbContext de façon implicite. Donc soit toute une requette et un DbContext sont discard, soit il est bon, mais on peut pas faire son marché dans un DbContext.
