### ISSUE TITLE
Introspection in fields parser doesn't work well 

### ISSUE THREAD

**Issue by jbbeuzelin** [LuccaSA/RestDrivenDomain#2]
Fields = new Field<A>(a=> a.b.c) doesn't load childs c in the object b.

**Comment by nfaugout** [comment]
C'est toujours valable ça ? Hier tu semblais tester et voir qu'en fait ça marchait...

**Comment by jbbeuzelin** [comment]
Hier, j'ai eu un problème quand je demande le paging et je ne l'ai plus eu quand je ne le demande pas. 

Mais mon cas là c'est quand on le demande dans le code directement : une collection appelle une autre collection en passant les fields à la mano.

**Comment by jbbeuzelin** [comment]
C'est bon en faîte, ce problème venait que tu utilisais directement le RestCollection et non le repo.
