### ISSUE TITLE
Ientitybase et interface minimale pour une api

### ISSUE THREAD

**Issue by Poltuu** [LuccaSA/RestDrivenDomain#207]
L'interface minimal à remplir pour être exposée dans un webcontroller, Ientitybase, est un sujet d'accrochage, sur quasiment chacun de ses membres:
   - Id : RAS. Néanmoins, le fait qu'il soit overridé lorsque l'on fait hériter ses objets de "EntityBase" est peu élégant. Je pense qu'on pourrait enlever le abstract de champ sur EntityBase
   - Name : ce champ n'a pas toujours de sens, et ne devrait donc pas être imposé aux ressources qui n'y trouvent aucun sens. 
   - Url : ce champ a été fortement source de friction, car il faut l'ignorer dans le dbcontext, ce qui est fait automatiquement dans le monolithe. On devrait rajouter [NotMapped] sur EntityBase pour commencer, mais encore mieux, se demander si l'on ne peut pas faire autrement, car il est également remonté qu'il est paru contre intruitif qu'un objet métier du domain ait à exposer un Url. Je pense qu'un traitement au niveau de la couche Web aurait plus de sens. Cette remarque rentre en écho avec les problèmes de perfs remontés par raph.
   - GetId() : hérité du monolithe, ce champ est utilisé par l'urlprovider uniquement. Je pense que l'on peut faire sans, ou qu'une refonte de la gestion du champ url permettra de s'en débarasser.
   - SetId() : jamais utilisé si ce n'est en test, à supprimer

De manière général, il est vraiment dommage qu'il soit nécessaire d'implémenter l'interface Ientitybase pour manipuler rdd, alors que le système pourrait concrètement faire sans quasi tout aussi bien. Cette expérience a révélé à mes yeux tout l'intérêt d'une approche telle que celle suggérée par raph, qui fonctionnerait par convention avant tout, par interface si ça arrange, et avec override via fluent api dans de rares cas.

**Comment by GMouron** [comment]
> * intruitif

intruitif ? 🤔  intrusif ?

**Comment by GuillaumeNury** [comment]
Autre remarque sur Url, sur Poplee Talent, elles sont fausses car il manque le préfixe `/popleetalent`.
(C'est peut-être overridable de façon globale ?)

**Comment by nfaugout** [comment]
@Poltuu je vois bien qu'il y a un consensus qui se dégage pour dire que tout ça n'est pas pratique et/ou pas à sa place.

En gros la question que pose @rducom dans son [issue similaire sur le sujet](https://github.com/LuccaSA/RestDrivenDomain/issues/193) et une de ses PR, c'est le découplage entre comment fonctionne le Domain dans RDD et la façon dont on l'expose via la couche Web. Par ex pouvoir exposer des valueObjects via une réponse JSON similaire à une réponse JSON de collection d'entités (noeud header, noeud data & co).

Le DDD prône l'indépendance total du Domain (ou en tout cas du Model du Domain) envers tout monde extérieur. Ca va dans votre sens.

Ce que je voudrais éviter en revanche, c'est qu'on se mettre à exposer tout et n'importe quoi via des API racine exposées sur des routes type `/api/xxx`.

Il faut donc qu'on trouve un compromis pour à la fois virer certaines contraintes, mais en garder quand même d'autres.

Si on regarde ce qui reste actuellement dans EntityBase...pas grand chose !

On pourrait donc :

- virer cette classe
- n'imposer comme contrainte sur le controllers d'API que le type TEntity doit implémenter IEntityBase
- n'avoir sur IEntityBase que Id en get;/set; et Name en get;
- gérer les Url uniquement dans la couche web

**Comment by rducom** [comment]
@GuillaumeNury adressé ici : https://github.com/LuccaSA/RestDrivenDomain/issues/210

**Comment by Poltuu** [comment]
ok ça me va.

Pour virer le champ url, cela veut dire:
 - remplacer ExpressionTree -> Tree<string>, comme déjà fait dans plusieurs PR, car sinon un requête du style fields=id,name,url planterait car url n'est pas une propriété. Cela a déjà été fait dans différentes PR et n'est pas douloureux, en plus d'être très bon pour les perfs
 - peut-être en profiter pour revoir le urlprovider pour qu'il n'ait les problèmes de perfs que tu as trouvé hier @rducom ?

**Comment by rducom** [comment]
Je propose de gérer URL dans une autre PR, une fois que la serialization sera découplée.

- ExpressionTree -> Tree : je propose ici une implémentation "weak", c'est à dire sans adhérence au type, permettant ainsi de ne pas avoir de plantage en phase de parsing de fields en cas de propriété manquante : https://github.com/LuccaSA/RestDrivenDomain/pull/141/files#diff-f2b0e032df628ba5180f2d433bdb995cR14
- Pour rappel, voici mon implémentation de l'injection Url: https://github.com/LuccaSA/RestDrivenDomain/pull/141/files#diff-3220217656043c09c326e529d05d74d3R37
(on discutera des détails genre renomage ou non du champ à ce moment)

**Comment by Poltuu** [comment]
on supprimera la propriété Url dans une autre pr costaud

**Comment by Poltuu** [comment]
Pour supprimer cette propriété des objets, deux voies:
 - soit on continue de supporter (au moins ne pas planter) sur des urls du style api/xxx?url=xxx&ordreby=url,asc&fields=url
 - soit on fait planter du jour au lendemain ces urls.

Probablement qu'on peut les laisser planter, sauf fields=url.
Pour continuer de supporter fields=url, il faut que le expressionparser supporte/comprenne ce mot clé, ou que ce mot clé soit pré enlevé de la requête par genre le queryparser, ou encore mieux, la couche web.

Ou bien, changement de paradigme, on affiche toujours l'url sur les obejts de type entitybase, qu'on les demande ou pas. Par contre, on ne peut plus requêter dessus.
Ces cas est le plus simple, car alors, c'est le serializer qui se charge de rajouter cette propriété tou seul sur ces objets.

Bref, il faut choisir.

en attendant, il faut que les objets implémentent implicitement cette propriété, sur laquelle s'appuie divers composants rdd
