### ISSUE TITLE
Consistance Url & Perfs Influx

### ISSUE THREAD

**Issue by rducom** [LuccaSA/RestDrivenDomain#210]
Actuellement Influx est utilisé pour déterminer la route d'une Uri d'une entité pour alimenter le champs URL.
Cet appel a un coût énorme. (5%)
D'autre part, déterminer le nom d'une route à partir de convention grammaticale ne permet en rien de garantir que la route retournée existe.
Il faut donc basculer sur une récupération des routes disponibles par controller / entité pour extraire la base du contenu qui sera utilisé pour le champ Url
Cette mécanique existe dans aspnet core et backé par une mise en cache, permettra d’être beaucoup plus efficace

**Comment by Poltuu** [comment]
cette modification va dans le sens des remarques que j'ai recu de mon côté, à savoir que le champ url n'avait de sens dans le domain, et qu'il polluait les objets métiers, quand bien même il est apprécié dans le retour d'api.

Je pense que l'on peut revoir la partie serialization sur la partie concernant l'url pour augmenter les perfs, l'exactitude de ce qui est retourné ET la beauté conceptuelle de ce que l'on propose.

**Comment by nfaugout** [comment]
Je suis d'accord avec vous sur ça, si on remonte le calcul des URL sur la couche web alors on peut profiter des Attributs type ["legalEntities"] qui indiquent sur quelle route on se trouve, et ainsi computer des URL d'entités en utilisant l'attribut non ? Après ça ira pas forcément plus vite si ?

**Comment by rducom** [comment]
L'idée c'est de récup les routes des controllers via aspnet qui expose tout le nécessaire pour ce faire (on connait le type controlleur, type retour des méthodes, route déclarée etc)

Il faut se faire injecter un `IActionDescriptorCollectionProvider`, puis parcourir `ActionDescriptors.Items[AttributeRouteInfo]`. Partant de là constituer un cache (dic) de type en clé, et string de path pour le GetById en valeur, prêts à recevoir un String.Format (càd contenant un {0} ) avec pour paramètre l'id.

L'avantage est double : 
- être garanti que le nom de la route corresponds à une vrai route
- les perfs seront vraiment plus rapides

Et on peut éventuellement imaginer à terme ne pas exposer d'URL si l'entité n'a pas de GetById (mais c'est un autre débat)

**Comment by nfaugout** [comment]
Deal !

**Comment by Poltuu** [comment]
j'ai déjà utilsié ces objets dans les tests, je vois très bien à quoi ça pourrait ressembler

**Comment by Poltuu** [comment]
fixé
