### ISSUE TITLE
Follow for GitHub

### ISSUE THREAD

**Issue by nfaugout** [LuccaSA/RestDrivenDomain#235]
Suite à la PR qui change la structure des projets, tout l'historique semble perdu du point de vue de GitHub.

Alors que l'historique Git lui est bien là !

C'est adressé sur cette issue : https://github.com/isaacs/github/issues/900

Et y'a une extension Chrome pour palier cette feature manquante sur GitHub : https://chrome.google.com/webstore/detail/follow-for-github/agalokjhnhheienloigiaoohgmjdpned/related

Et ça marche nickel !

Un bouton Follow apparaît :

![chrome_2018-10-16_11-24-42](https://user-images.githubusercontent.com/2686141/47006402-1d9bf780-d136-11e8-8f2f-84cd9488a5ae.png)

Suffit de cliquer dessus : 

![chrome_2018-10-16_11-25-23](https://user-images.githubusercontent.com/2686141/47006435-2e4c6d80-d136-11e8-8d05-b6d79e2943a2.png)

**Comment by rducom** [comment]
Quand tu blame dans github on a bien l'historique

**Comment by nfaugout** [comment]
Bien vu en effet, le Blame fonctionne.

Le plugin reste intéressant pour l'Historique.

**Comment by rducom** [comment]
@nfaugout on peux close l'issue ?
