### ISSUE TITLE
Library Guidance

### ISSUE THREAD

**Issue by nfaugout** [LuccaSA/RestDrivenDomain#239]
M$ a publié une série d'articles qui donnent des bonnes pratiques sur la façon de publier une "bonne" librairie : https://docs.microsoft.com/fr-fr/dotnet/standard/library-guidance/

Ce serait intéressant de voir à quel point on respecte les différents points et faire les ajustements.

Merci @GMouron pour le poke.

**Comment by rducom** [comment]
Yes, c'est apparu sem dernière et y'a eu débat sur tweeter sur le strong signing.
Les 2 points qui nous manquent :
- Pour les refs nugets, oui on pourrait référencer le .Minor des versions en flottant pour les libs externes, ça permettrait d'éviter des montées de version du côté de nos libs. Par contre, nous ne sommes pas suffisamment rigoureux sur nos propres libs (sur les breaking changes) pour les référencer en minor flottant
- Pour le strong signing, pour l'instant on va mettre de côté, on a aucun avantage à signer nos assemblys pour l'instant
