### ISSUE TITLE
AppController.SaveChangesAsync()

### ISSUE THREAD

**Issue by nfaugout** [LuccaSA/RestDrivenDomain#240]
@rducom cette méthode sur le AppController est déconcertante car elle demande en paramètre un IEnumerable d'entités. Auparavant quand on appelait directement le SaveChangesAsync du IStorageService ou du IUnitOfWork, on n'avait rien besoin d'envoyer en paramètres.

Il faut donc au minimum une version de SaveChangesAsync qui ne prend pas de paramètre et qui appelle l'autre avec une liste vide, pour éviter que chaque AppController doivent envoyer une liste vide à chaque fois qu'il veut commiter.

Et idéalement il ne faut pas avoir besoin d'envoyer des entités, car dans le OnBeforeSaveEntitiesAsync si tu as besoin d'aller chercher les entités qui vont être persistées, tu peux probablement le faire en demandant à EF les entités à l'état Modified ou équivalent.

**Comment by rducom** [comment]
100% ok, mais ça soulève le point de design suivant : IUnitOfWork va introduire une méthode retournant les objets créés/modifiés, qu'on ne pourra pas implémenter sur le InMemoryStorageService. Je pense toujours qu'on devrait se débarrasser de cette classe

**Comment by nfaugout** [comment]
Je ne vois pas le rapport avec InMemoryStorageService. On peut le virer sans pb et en effet utiliser le InMemory de EF, mais c'est hors sujet ici.

**Comment by rducom** [comment]
Le rapport est le suivant : actuellement il ne permet pas de dissocier les entités persistées in-memory des entités modifiées dans le contexte courant. On ne peut donc pas introduire sur IUnitOfWork une méthode retournant les objets créés/modifiés d'un InMemoryStorageService

**Comment by rducom** [comment]
> comment tu ferais avec un IUnitOfWork "EF" pour envoyer les entités à OnBeforeSaveChanges sans avoir joué le SaveChanges ?

En introduisant une méthode sur IUnitOfWork retournant les objets créés/modifiés

**Comment by nfaugout** [comment]
Ah je vois, tu veux plutôt dire les objets "candidats" à création/modification, en gros les objets trackés par EF et qui vont être pris en compte au moment du SaveChanges.

Ca se défend, si tu veux tu peux faire cette modif, ajouter la méthode SaveChanges( ) sans param, et virer le InMemoryStorageService, je sais que ça te fera plaisir :D

**Comment by Poltuu** [comment]
J'attends moi aussi cette modif avec plaisir, j'ai fait la même constatation que toi nico en mettant en place le truc sur poplee talent, un SaveChanges() sans pram doit exister

**Comment by rducom** [comment]
Resolved by https://github.com/LuccaSA/RestDrivenDomain/pull/253
