### ISSUE TITLE
Protection pour services.GetService<IService>()

### ISSUE THREAD

**Issue by nfaugout** [LuccaSA/RestDrivenDomain#242]
Dans certains fichiers on résout des dépendances at runtime, [par ex dans RddJonsResult](https://github.com/LuccaSA/RestDrivenDomain/blob/master/src/Rdd.Web/Serialization/RddJsonResult.cs#L99).

Ce serait bien de protéger ces résolutions avec des throw explicites (comme ceux du framework d'injection qui sont très clairs) au cas où par erreur ces interfaces ne sont pas enregistrées, soit par un oubli de .AddRdd( ) soit par un BUG dans la DI de Rdd.

**Comment by Poltuu** [comment]
ya une issue connexe, c'est de virer AddRddCore, car rddcore n'est pas auto-suffisant sans la serialization, donc il faut lui rajouter la serialization, ce qui fait qu'il équivaut alors à .AddRdd

**Comment by Poltuu** [comment]
fixed
