### ISSUE TITLE
CreateAsync avec une entité en param

### ISSUE THREAD

**Issue by vergerf** [LuccaSA/RestDrivenDomain#252]
Actuellement, je ne peux pas appeler le CreateAsync en lui passant une entité.
C'est plutôt problématique lorsque je manipule des objets instanciés depuis la couche Application, c'est pas naturel de créer un Candidate de toute pièce.

Il me semble qu'il y a eu des discussions sur le sujet :/
https://github.com/LuccaSA/RestDrivenDomain/issues/238

**Comment by nfaugout** [comment]
Oui je suis d'accord avec toi, tu dois créer une Candidate et setter son .Value avec ton entité.

Et il ne faudra pas que tu oublies d'injecter un IInstanciator custom sous peine de voir ton Candidate tout simplement ignoré par la Collection ! Regarde ce code, il ignore le candidate passé en param : https://github.com/LuccaSA/RestDrivenDomain/blob/master/src/Rdd.Domain/Models/DefaultInstanciator.cs#L6

J'ai eu le même pb que toi et j'ai dû overrider : https://github.com/LuccaSA/Lucca.Auth/blob/master/Auth/v2/Domain/Auth.v2.Domain/Collections/MobileTokensInstanciator.cs#L11

**Comment by vergerf** [comment]
Je suis finalement passé par un service qui fais le travaille pour moi.
Il y avait un besoin métier.

**Comment by rducom** [comment]
Les prototypes de méthodes Create/Update/Delete prenant uniquement des instances de T en entrée, ont été supprimés récemment, mais je suis d'avis de les réintroduire. Ils sont indispensables pour une bonne expérience développeur, et on a pas envie de passer par un Candidate lorsqu'on fait un appel à une collection / repo depuis la couche Application.
Ce besoin est un cas d'usage très fréquent

**Comment by nfaugout** [comment]
Je viens de tomber sur le même que toi @vergerf en mettant à niveau Lucca.Auth sur Rdd v3.0

J'en arrive à la même conclusion que @rducom, après avoir relu les 2 issues en rapport avec le sujet (https://github.com/LuccaSA/RestDrivenDomain/issues/238 et https://github.com/LuccaSA/RestDrivenDomain/issues/259).

Voici mon point de vue du jour :
- remonter ICandidate/Candidate uniquement dans les couches Web et Application. Web instancie un Candidate à partir du JSON qui arrive en entrée, Application travaille sur un ICandidate et gère une étape de validation (qui reste dans le TEntity du Domain).
- si la validation est concluante, alors Application appelle le CreateAsync du Domain (sur la collection) avec un TEntity et non plus un ICandidate

Ce qui revient à ce que propose Raph, càd réintroduire des méthodes Create & co avec des TEntity, mais en allant plus loin, càd en virant les méthodes actuelles qui prennent un ICandidate.

En attendant je vais créer une classe dans mon Domain Lucca.Auth qui implémente ICandidate et qui renvoie l'entité que j'ai sous la main dans son .Value et qui throw sur toutes les autres propriétés/méthodes.

**Comment by bebelz** [comment]
Je viens aussi de tomber dans un cas ou je suis bloqué par la signature de cette méthode.

@nfaugout as-tu pu implémenter un ICandidate en attendant que RDD propose les méthodes en question ?

**Comment by nfaugout** [comment]
Oui, mais pas encore pushé, voici le code

````

    public class DomainCandidate<TEntity, TKey> : ICandidate<TEntity, TKey>
		where TEntity : IEntityBase<TKey>
	{
		TEntity _entity;

		public DomainCandidate(TEntity entity)
		{
			_entity = entity;
		}

		TKey ICandidate<TEntity, TKey>.Id => _entity.Id;
		object ICandidate<TEntity>.Id => _entity.Id;
		TEntity ICandidate<TEntity>.Value => _entity;
		JsonObject ICandidate<TEntity>.JsonValue => throw new NotImplementedException();
		bool ICandidate<TEntity>.HasId() { return true; }
		bool ICandidate<TEntity>.HasProperty<TProp>(Expression<Func<TEntity, TProp>> expression) { throw new NotImplementedException(); }
	}
````

**Comment by bebelz** [comment]
Je te la pique, merci :)

**Comment by nfaugout** [comment]
Tu devrais demander à @Poltuu moi j'en ai pas eu besoin d'où mon implémentation.

En gros il faut partir de _entity et faire un .ToJson ou équivalent, Romain va savoir quoi faire.
