### ISSUE TITLE
filter on mailmessages don't work anymore

### ISSUE THREAD

**Issue by BenjaminLY** [LuccaSA/RestDrivenDomain#272]
```c#
//marche - requete sur champ string sous-jacent directement
				query.Filter = new Filter<User>(u => u.MailAsString == "test2@lucca.fr");

//marche - ancienne version
				var mails = new List<MailAddress> { new MailAddress("test2@lucca.fr") };
				query.Filter = new Filter<User>(u => mails.Contains(u.Mail));
// ne marche pas
				var mail = new MailAddress("test2@lucca.fr");
				query.Filter = new Filter<User>(u => u.Mail == mail);
//ne marche pas
				query.Filter = new Filter<User>(u => u.Mail == new MailAddress("test2@lucca.fr"));
```

le filtres sur mailmessage ne fonctionnenet plus

**Comment by nfaugout** [comment]
@BenjaminLY tu es sur quelle version de RDD ?

Sur le master je n'ai pas de pb. J'ai fait un test pour reproduire ton code et ça semble fonctionner.

**Comment by BenjaminLY** [comment]
@nfaugout on a vu ça ensemble avec @Poltuu.
Bug remonté sur la version RDD `3.0.0-preview.7`

En fait, il s'agissait de tests sur le projet Lucca.Auth/auth-v2, qui tournaient sur RDD `3.0.0-preview.4`.
On a upgrade la version de RDD et c'est là que l'on a constaté ce bug.

**Comment by nfaugout** [comment]
OK tu peux pousser une branche de auth-v2 sur laquelle le test fail pour que je puisse reproduire et comprendre ce qui se passe ?

**Comment by Poltuu** [comment]
je m'occupe du fix, avec sa suite de tests of course
