### ISSUE TITLE
Count pour faire un Any ?

### ISSUE THREAD

**Issue by ThibautRappet** [LuccaSA/RestDrivenDomain#300]
Si je comprends bien le code, on fait un `Count` pour faire le `Any`, ce qui peut avoir un très gros impact au niveau des perfs. Il y a une raison derrière ça ?

https://github.com/LuccaSA/RestDrivenDomain/blob/6c3a69ed9e22901e06a14a8c32ac2f87e8913d13/src/Rdd.Domain/Models/ReadOnlyRestCollection.cs#L25

**Comment by Poltuu** [comment]
non en effet.
tu peux corriger. Il faut rajouter les méthodes AnyAsync sur la collection et le repo.

**Comment by nfaugout** [comment]
@Poltuu on n'avait pas justement détecter que le .Count était plus performant qu'un .Any( ) y'a qq mois voire une année ? Ca me rappelle vaguement qq chose.

@rducom une idée ?

**Comment by nfaugout** [comment]
#good first pr => lol

**Comment by rducom** [comment]
Le Any() sera traduit par un IF EXISTS(SELECT ... ) donc indeed (bcp) plus rapide qu'un Count.
@ThibautRappet go go go ! 🚀

**Comment by Poltuu** [comment]
@nfaugout y avait bien un truc du genre, mais ct pas sur des requêtes sql, ct dans un coin sombre du legacy :)
