### ISSUE TITLE
Internal set should forbid property's edit

### ISSUE THREAD

**Issue by lmaquin** [LuccaSA/RestDrivenDomain#357]
When sending a PUT | POST request, I'm able to edit all properties on a resource, even those with internal setters.
Can you fix this please 🙏

**Comment by Poltuu** [comment]
Fixable. the question is : 3.4 or 4.0 ?

**Comment by nfaugout** [comment]
For me it's a BUG, so 3.4 should be preferred, even if it will break 
unintentional uses.
