### ISSUE TITLE
Serialization: typo

### ISSUE THREAD

**Issue by dpetiteau** [LuccaSA/RestDrivenDomain#363]
La typo se trouve sur cette ligne, il manque une virgule dans les types génériques sur le test ` typeof(ReadOnlyWebController<,>) == definition` :

https://github.com/LuccaSA/RestDrivenDomain/blob/8e77378b73b756165e800c130c894d92f59df78c/src/Rdd.Web/Serialization/UrlProviders/UrlProvider.cs#L90

Nous avons des sous-ressources dont les controllers héritent directement de ReadOnlyWebController<TAppController,TEntity,TKey> mais nous avons remarqué que la sérialisation de la propriété Url ne se faisait pas. 

Le problème vient de cet oubli de virgule qui permettra de vérifier également le type ReadOnlyWebController<,,>

**Comment by Poltuu** [comment]
thanks
