### ISSUE TITLE
Hide the url path in the json response of one object 

### ISSUE THREAD

**Issue by jbbeuzelin** [LuccaSA/RestDrivenDomain#5]
When you ask this /api/something/1, you still have the url path of this object in the response, for me it's a mistake ?

**Comment by nfaugout** [comment]
Tu veux dire que quand on demande 1 seule ressource, genre /api/users/123 alors il ne faudrait pas renvoyer la propriété .url de cette ressource ?

Pour moi cette propriété de la ressource au même titre que son ID, ID que tu connais déjà quand tu demandes la ressource, et pour autant on le renvoie quand même ;)

Donc si c'est ça la question, alors je ne vois pas de problème à renvoyer l'url d'une ressource, qu'on ait fait un appel sur la collection ou sur une ressource en particulier.

**Comment by jbbeuzelin** [comment]
Exactement, c'est exactement ma question. Comme avant tu n'avais pas ça (de mémoire), je pensais que c'était une erreur.

**Comment by nfaugout** [comment]
Y'a toujours eux la prorpriété url dans une ressource, qu'elle soit dans une collection ou toute seule ;)

Après ça dépend des fields que tu demandes
