### ISSUE TITLE
Async methods for WebClient

### ISSUE THREAD

**Issue by versinia** [LuccaSA/RestDrivenDomain#51]
The [IWebClient interface](https://github.com/LuccaSA/RestDrivenDomain/blob/5e4b76e004c4113bf78b6b3402cad8b158b2e579/RDD.Domain/IWebClient.cs) lacks async methods. I suggest declaring new methods that will mirror existing ones, using async/await and returning `Task<>`s.

**Comment by nfaugout** [comment]
Resolved by https://github.com/LuccaSA/RestDrivenDomain/pull/114
