### ISSUE TITLE
Don't show all fields when requesting one entity

### ISSUE THREAD

**Issue by nfaugout** [LuccaSA/RestDrivenDomain#53]
This is how it works now :

- GET /api/users => only id, name & url fields are shown
- GET /api/users?fields=id,name => on id & name fields are shown
- GET /api/users/123 => ALL fields, calculated on the user object are shown

My problem with the later is that we don't have any clue about which fields are used by the issuer of the request.

In order to track more precisely which fields are under use (into Logmatic for instance), I suggest that "fields" parameter become mandatory. In other words, if you don't specify the "fields" parameter, a query on one entity will return only id, name, url, as any collection request, forcing the issuer to precise which fields he wants.

This way, we can keep track of which issuer use which fields, and contact them in case of an upcoming breaking change or deprecation of field

**Comment by jbbeuzelin** [comment]
Agreed with this. 

But i'm used to see one entity to see all available fields on it. I think all front developper do the same.

So this response need to come with an automatic documentation (for example, swagger) to help developer to consume API.

**Comment by nfaugout** [comment]
+1 => https://github.com/LuccaSA/RestDrivenDomain/issues/54
