### ISSUE TITLE
MOD : PropertySelector

### ISSUE THREAD

**Issue by nfaugout** [LuccaSA/RestDrivenDomain#79]
Cette classe permet à la fois d'avoir N niveaux de profondeur (u => u.Manager.Department.Name), et à la fois plusieurs délégués (u => u.Name, u => u.Manager.Department.Name, u => u.Manager.Id, ..)

On devrait la simplifier pour ne gérer que la profondeur, et on gérerait la liste de délégués à l'extérieur, via un IEnumerable<PropertySelector> par exemple.

Ca complexifie un tout petit peu Field.cs, mais ça permet de simplifié à mort cette classe.

**Comment by Poltuu** [comment]
done
