### ISSUE TITLE
FIX HttpStatusCodeExceptionMiddleware

### ISSUE THREAD

**Issue by nfaugout** [LuccaSA/RestDrivenDomain#92]
Le middleware qui catch les exceptions ne renvoie pas du JSON bien formé, mais uniquement le message brut de l'exception.

cf https://github.com/LuccaSA/RestDrivenDomain/blob/master/Web/RDD.Web/Helpers/HttpStatusCodeExceptionMiddleware.cs#L72

Il faudrait qu'il encapsule le message d'erreur dans un objet JSON.

**Comment by nfaugout** [comment]
@rducom ça je pense que c'est réglé mais j'en suis pas sûr à 100%, tu pourras nous dire ?

**Comment by rducom** [comment]
C'est disponible via la méthode [UseRdd() ](https://github.com/LuccaSA/RestDrivenDomain/blob/master/src/Rdd.Web/Helpers/RddServiceCollectionExtensions.cs#L118)
