### ISSUE TITLE
RDD v2.2 - #4 Linéariser PropertySelector

### ISSUE THREAD

**Issue by nfaugout** [LuccaSA/RestDrivenDomain#98]
PropertySelector est un wrapper d'Expression pour indiquer qu'on sélectionne une propriété assez profonde dans une lignée d'objets (ex : u => u.Department.Members.Select(m => m.Name))

Interroger l'expression directement en quête de savoir si elle contient tel ou tel accesseur est délicat. C'est l'objet de PropertySelector.

Le pb c'est qu'au lieu de ne contenir qu'une seule Expression, il en contient N, et ça nuit à sa simplicité je trouve.

J'aimerais donc notamment que Fields se repose sur une collection de PropertySelector plutôt qu'un seul PropertySelector !

Ca permet de simplifié PropertySelector et de l'utiliser pour d'autres usages par la suite, notamment dans les Candidates.

Pour préciser ce que je propose, PropertySelector serait une structure récursive avec une relation 1-1 parent/enfant.

Par ex u => u.Department.Name serait porté par un PropertySelector (u => u.Department), qui contiendrait un 2ème PropertySelector (d => d.Name).

**Comment by GMouron** [comment]
Faut faire attention avec ça, c'est pas super facile à mettre en place pour que EF soit content avec ce que tu lui donnes à manger.
Bref, ça a l'air simple sur le papier mais l'implémentation est plus compliquée qu'on ne le croit :)

**Comment by nfaugout** [comment]
Je ne vois pas de quoi tu parles, ça marche déjà en prod, et ce que je propose de faire, c'est de déshabiller PropertySelector en virant son côté arbre pour un faire un simple objet récursif.

Donc à priori on simplifie les choses, donc pas d'inconnu.

**Comment by Poltuu** [comment]
l'objet a été revu et amélioré, coupé en plusieurs composants
